load("@rules_pandoc//pandoc:pandoc.bzl", "pandoc")

pandoc(
    name = "ex001_docx",
    srcs = ["ex001.md"],
    format = "docx",
)

pandoc(
    name = "ex001_html",
    srcs = ["ex001.md"],
    format = "html",
)

pandoc(
    name = "ex001_typst",
    srcs = ["ex001.md"],
    format = "typst",
)
