"""Populate pandoc/private/versions.bzl.

Run with no arguments to list the pandoc versions available on GitHub:

    bazel run //tools/update_versions

Run with a version to add (or refresh) that version's entries for all
supported architectures:

    bazel run //tools/update_versions -- 3.10

For each architecture the script finds the release asset, downloads it to a
temporary directory, computes the Bazel integrity (sha256), extracts it to
discover the archive's strip_prefix, and then discards the download.
"""

import argparse
import base64
import hashlib
import json
import os
import re
import tarfile
import tempfile
import urllib.request
import zipfile
from pathlib import Path

REPO = "jgm/pandoc"
HEADERS = {"User-Agent": "rules_pandoc-update-versions"}

# Optional token to avoid the low anonymous GitHub API rate limit.
if os.environ.get("GITHUB_TOKEN"):
    HEADERS["Authorization"] = "Bearer {}".format(os.environ["GITHUB_TOKEN"])

# Our platform key -> the asset filename suffix (after "pandoc-<version>-").
PLATFORMS = {
    "linux-x86_64": "linux-amd64.tar.gz",
    "linux-aarch64": "linux-arm64.tar.gz",
    "macos-x86_64": "x86_64-macOS.zip",
    "macos-aarch64": "arm64-macOS.zip",
    "windows-x86_64": "windows-x86_64.zip",
}

_VERSION_RE = re.compile(r"^\d+(\.\d+)*$")

_HEADER = '''"""Pandoc versions.

A mapping of version -> platform -> archive metadata used by the module
extension to fetch pandoc binaries.

AUTO-GENERATED by //tools/update_versions. To add a version:

    bazel run //tools/update_versions -- <version>

Recognized platform keys:
    linux-x86_64, linux-aarch64, macos-x86_64, macos-aarch64, windows-x86_64
"""
'''


def _workspace_root():
    if "BUILD_WORKSPACE_DIRECTORY" in os.environ:
        return Path(os.environ["BUILD_WORKSPACE_DIRECTORY"])
    return Path(__file__).resolve().parents[2]


def _semver_key(version):
    return tuple(int(p) for p in version.split("."))


def _get_json(url):
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())


def list_versions():
    """Return all numeric pandoc release tags, newest first."""
    versions = []
    page = 1
    while True:
        data = _get_json(
            "https://api.github.com/repos/{}/releases?per_page=100&page={}".format(
                REPO, page
            )
        )
        if not data:
            break
        for release in data:
            tag = release.get("tag_name", "")
            if _VERSION_RE.match(tag):
                versions.append(tag)
        page += 1
    return sorted(set(versions), key=_semver_key, reverse=True)


def _assets_for(version):
    """Map asset name -> download URL for a release tag."""
    data = _get_json(
        "https://api.github.com/repos/{}/releases/tags/{}".format(REPO, version)
    )
    return {a["name"]: a["browser_download_url"] for a in data.get("assets", [])}


def _download_and_hash(url, dest):
    """Stream url to dest, returning the Bazel integrity value."""
    req = urllib.request.Request(url, headers=HEADERS)
    digest = hashlib.sha256()
    with urllib.request.urlopen(req) as resp, open(dest, "wb") as out:
        while True:
            chunk = resp.read(1 << 20)
            if not chunk:
                break
            digest.update(chunk)
            out.write(chunk)
    return "sha256-" + base64.b64encode(digest.digest()).decode("utf-8")


def _strip_prefix(archive):
    """The single top-level directory in the archive, or '' if there isn't one."""
    if archive.endswith(".zip"):
        with zipfile.ZipFile(archive) as zf:
            names = zf.namelist()
    else:
        with tarfile.open(archive) as tf:
            names = tf.getnames()
    tops = {name.split("/")[0] for name in names if name}
    return tops.pop() if len(tops) == 1 else ""


def build_version(version):
    """Return the {platform: entry} mapping for a single version."""
    assets = _assets_for(version)
    platforms = {}
    with tempfile.TemporaryDirectory() as tmp:
        for key, suffix in PLATFORMS.items():
            name = "pandoc-{}-{}".format(version, suffix)
            url = assets.get(name)
            if not url:
                print("  skip {}: no asset {}".format(key, name))
                continue
            archive = os.path.join(tmp, name)
            integrity = _download_and_hash(url, archive)
            platforms[key] = {
                "urls": [url],
                "integrity": integrity,
                "strip_prefix": _strip_prefix(archive),
            }
            os.remove(archive)
            print("  {} -> {}".format(key, integrity))
    return platforms


def _load_existing(path):
    if not path.exists():
        return {}
    namespace = {}
    exec(compile(path.read_text(), str(path), "exec"), namespace)
    return namespace.get("PANDOC_VERSIONS", {})


def _render(versions):
    lines = [_HEADER, "", "PANDOC_VERSIONS = {"]
    for version in sorted(versions, key=_semver_key):
        lines.append('    "{}": {{'.format(version))
        for platform in sorted(versions[version]):
            entry = versions[version][platform]
            urls = ", ".join('"{}"'.format(u) for u in entry["urls"])
            lines.append('        "{}": {{'.format(platform))
            lines.append('            "urls": [{}],'.format(urls))
            lines.append('            "integrity": "{}",'.format(entry["integrity"]))
            lines.append('            "strip_prefix": "{}",'.format(entry["strip_prefix"]))
            lines.append("        },")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "version",
        nargs="?",
        help="Version to add. If omitted, list available versions.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_workspace_root() / "pandoc/private/versions.bzl",
        help="Path to versions.bzl to update.",
    )
    args = parser.parse_args()

    if not args.version:
        for version in list_versions():
            print(version)
        return

    print("Resolving pandoc {}".format(args.version))
    platforms = build_version(args.version)
    if not platforms:
        raise SystemExit("No assets found for version {}".format(args.version))

    versions = _load_existing(args.output)
    versions[args.version] = platforms
    args.output.write_text(_render(versions))
    print("Wrote {} ({} platforms)".format(args.output, len(platforms)))


if __name__ == "__main__":
    main()
