"""Pandoc versions.

A mapping of version -> platform -> archive metadata used by the module
extension to fetch pandoc binaries.

AUTO-GENERATED by //tools/update_versions. To add a version:

    bazel run //tools/update_versions -- <version>

Recognized platform keys:
    linux-x86_64, linux-aarch64, macos-x86_64, macos-aarch64, windows-x86_64
"""


PANDOC_VERSIONS = {
    "3.10": {
        "linux-aarch64": {
            "urls": ["https://github.com/jgm/pandoc/releases/download/3.10/pandoc-3.10-linux-arm64.tar.gz"],
            "integrity": "sha256-VUE9+wwa7IYWQf6Fjx9z6EhI89tJexwMAuYoh+p29KQ=",
            "strip_prefix": "pandoc-3.10",
        },
        "linux-x86_64": {
            "urls": ["https://github.com/jgm/pandoc/releases/download/3.10/pandoc-3.10-linux-amd64.tar.gz"],
            "integrity": "sha256-4PivYtDyZ9IrqlvO/m1d2joJfMxg3nlLdZ/gMVmSMkQ=",
            "strip_prefix": "pandoc-3.10",
        },
        "macos-aarch64": {
            "urls": ["https://github.com/jgm/pandoc/releases/download/3.10/pandoc-3.10-arm64-macOS.zip"],
            "integrity": "sha256-2crQHZaud0oNyMjEW7GtPkxf8swuJPRZWPX5t5dK7jQ=",
            "strip_prefix": "pandoc-3.10-arm64",
        },
        "macos-x86_64": {
            "urls": ["https://github.com/jgm/pandoc/releases/download/3.10/pandoc-3.10-x86_64-macOS.zip"],
            "integrity": "sha256-YzT02a98njfnYd+tVvpVB2hfbSlyTr8xxL5tXGVKMWE=",
            "strip_prefix": "pandoc-3.10-x86_64",
        },
        "windows-x86_64": {
            "urls": ["https://github.com/jgm/pandoc/releases/download/3.10/pandoc-3.10-windows-x86_64.zip"],
            "integrity": "sha256-u4CNAP1YdiKZ1kWCqbTD5LEGzZKeYsXxm83LSW8eVK4=",
            "strip_prefix": "pandoc-3.10",
        },
    },
}
